# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  inputs,
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    inputs.lanzaboote.nixosModules.lanzaboote
  ];

  services.scx = {
    enable = true;
    scheduler = "scx_bpfland";
    # scheduler = "scx_lavd";
    # extraArgs = [
    #   "--autopilot"
    # ];
  };

  boot = {
    initrd.systemd.enable = true;
    loader = {
      systemd-boot = {
        enable = lib.mkForce false;
        # enable = true;
        consoleMode = "keep";
      };
      efi.canTouchEfiVariables = true;
      timeout = 5;
    };

    kernelPackages = pkgs.linuxPackages_latest;
    initrd.availableKernelModules = [
      "nvme"
      "xhci_pci"
      "ahci"
      "usbhid"
      "usb_storage"
      "sd_mod"
    ];
    initrd.kernelModules = [
      "amdgpu"
      "ntsync"
    ];

    kernelModules = [
      "kvm-amd"
      "ntsync"
      "btintel"
      "v4l2loopback"
    ];

    kernelParams = ["amd_pstate=guided" "amdgpu.ppfeaturemask=0xffffffff" "amdgpu.aspm=0" "amdgpu.audio=0" "nmi_watchdog=0" "nowatchdog" "processor.max_cstate=1" "transparent_hugepage=never" "vm.zone_reclaim_mode=0" "audit=0" "pcie_aspm=off" "ignore_rlimit_data" "split_lock_detect=off" "split_lock_mitigate=0" "preempt=full" "libahci.ignore_sss=1" "loglevel=3" "rd.systemd.show_status=false" "transparent_hugepage_tmpfs=never" "amdgpu.dcdebugmask=0x4"];
    supportedFilesystems = [
      "nfs"
      "ext4"
      "btrfs"
      "ntfs"
    ];
    extraModulePackages = with config.boot.kernelPackages; [
      v4l2loopback
    ];
    extraModprobeConfig = ''
      options v4l2loopback exclusive_caps=1 card_label="Virtual Webcam"
    '';

    kernel.sysctl = {
      # The Magic SysRq key is a key combo that allows users connected to the
      # system console of a Linux kernel to perform some low-level commands.
      # Disable it, since we don't need it, and is a potential security concern.
      "kernel.sysrq" = 0;

      ## TCP hardening
      # Prevent bogus ICMP errors from filling up logs.
      "net.ipv4.icmp_ignore_bogus_error_responses" = 1;
      # Reverse path filtering causes the kernel to do source validation of
      # packets received from all interfaces. This can mitigate IP spoofing.
      "net.ipv4.conf.default.rp_filter" = 1;
      "net.ipv4.conf.all.rp_filter" = 1;
      # Do not accept IP source route packets (we're not a router)
      "net.ipv4.conf.all.accept_source_route" = 0;
      "net.ipv6.conf.all.accept_source_route" = 0;
      # Don't send ICMP redirects (again, we're not a router)
      "net.ipv4.conf.all.send_redirects" = 0;
      "net.ipv4.conf.default.send_redirects" = 0;
      # Refuse ICMP redirects (MITM mitigations)
      "net.ipv4.conf.all.accept_redirects" = 0;
      "net.ipv4.conf.default.accept_redirects" = 0;
      "net.ipv4.conf.all.secure_redirects" = 0;
      "net.ipv4.conf.default.secure_redirects" = 0;
      "net.ipv6.conf.all.accept_redirects" = 0;
      "net.ipv6.conf.default.accept_redirects" = 0;
      # Protects against SYN flood attacks
      "net.ipv4.tcp_syncookies" = 1;
      # Incomplete protection again TIME-WAIT assassination
      "net.ipv4.tcp_rfc1337" = 1;

      ## TCP optimization
      # TCP Fast Open is a TCP extension that reduces network latency by packing
      # data in the sender’s initial TCP SYN. Setting 3 = enable TCP Fast Open for
      # both incoming and outgoing connections:
      "net.ipv4.tcp_fastopen" = 3;
      # Bufferbloat mitigations + slight improvement in throughput & latency
      "net.ipv4.tcp_congestion_control" = "bbr";
      "net.ipv4.tcp_mtu_probing" = 1;
      "net.core.default_qdisc" = "cake";
      "net.core.netdev_max_backlog" = 16384; # increasing buffer where the kernel stores packets after they’ve been pulled off the physical network card (NIC) but before the CPU has had a chance to process them.
      # "net.core.rmem_max" = 16777216; # set max TCP/UDP receive buffer size.
      # "net.core.wmem_max" = 16777216; # set max TCP/UDP send buffer size.
      # "net.core.rmem_default" = 8388608; # set default TCP/UDP receive buffer size.
      # "net.core.wmem_default" = 8388608; # set default TCP/UDP send buffer size.
      # 20-shed.conf
      "kernel.sched_cfs_bandwidth_slice_us" = 3000;
      "kernel.printk_devkmsg" = "off";
      "kernel.printk" = "3 3 2 3"; #limits log messages to the important stuff, less overhead
      "kernel.kptr_restrict" = 1; # restricts viewing of kernel pointers to application which have CAP_SYSLOG capability or have root rights.
      "kernel.threads-max" = 1073741823; # sets max system thread count.

      # 20-net-timeout.conf
      # This is required due to some games being unable to reuse their TCP ports
      # if they're killed and restarted quickly - the default timeout is too large.
      "net.ipv4.tcp_fin_timeout" = 5;
      # 30-splitlock.conf
      # Prevents intentional slowdowns in case games experience split locks
      # This is valid for kernels v6.0+
      "kernel.split_lock_mitigate" = 0;
      # 30-vm.conf
      # USE MAX_INT - MAPCOUNT_ELF_CORE_MARGIN.
      # see comment in include/linux/mm.h in the kernel tree.
      "vm.max_map_count" = 2147483642;
      "vm.swappiness" = 1; # Says how strong the pressure is to put stale stuff in memory into Swap the lower the less the pressure
      "vm.stat_interval" = 10; # This parameter controls how often (in seconds) the kernel's virtual memory (VM) subsystem wakes up to recount and update its internal statistics.
      "vm.zone_reclaim_mode" = 0; # same as the command line parameter, maybe you dont even need this here if you have the commandline parameter
      "vm.compaction_proactiveness" = 0; # disables ram memory page defragmentation, this disables kcompactd which repeatedly checks and defragments the ram. Which can cause stutter, lag and hangs.
      "vm.overcommit_memory" = 1; # tell applications they can commit as much as they want. TLDR: Always say yes to memory allocations.
    };

    lanzaboote = {
      enable = true;
      pkiBundle = "/var/lib/sbctl";
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a9bc029b-2e9c-4c15-83bb-c8f30373f285";
    fsType = "btrfs";
    options = [
      "subvol=root"
      "compress=zstd"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/a9bc029b-2e9c-4c15-83bb-c8f30373f285";
    fsType = "btrfs";
    options = [
      "subvol=home"
      "compress=zstd"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/a9bc029b-2e9c-4c15-83bb-c8f30373f285";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D838-AE74";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  # fileSystems."/mnt/fanxiang" =
  #   { device = "/dev/disk/by-uuid/986a0426-7ef9-4758-9b76-a5cd2c3ca550";
  #     fsType = "btrfs";
  #     options = [ "compress=zstd" ];
  #   };

  # fileSystems."/mnt/nfs" = {
  #   device = "192.168.254.191:/mnt/media2";
  #   fsType = "nfs";
  #   options = [
  #     "x-systemd.automount"
  #     "noauto"
  #   ];
  # };

  # environment.systemPackages = [
  #   pkgs.cifs-utils
  #   pkgs.sbctl
  # ];
  #
  # fileSystems."/mnt/share" = {
  #   device = "//192.168.254.191/media";
  #   fsType = "cifs";
  #   options = let
  #     # this line prevents hanging on network split
  #     automount_opts = "x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s";
  #   in ["${automount_opts},credentials=/etc/nixos/smb-secrets"];
  # };

  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 16 * 1024;
    }
  ];

  services.btrfs.autoScrub = {
    enable = true;
  };

  hardware = {
    i2c.enable = true;
    amdgpu.overdrive.ppfeaturemask.enable = true;
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

    bluetooth = {
      enable = true;
      settings = {
        General = {
          Experimental = true;
          FastConnectable = true;
        };
        Policy = {
          AutoEnable = true;
        };
      };
    };
  };
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
