# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  boot.loader.grub = {
    enable = true;
    device = "/dev/sdb";
    useOSProber = true;
  };
  boot.initrd.systemd.enable = true;
  # boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.kernelModules = ["intel_pstate"];
  boot.extraModulePackages = [];
  boot.kernelParams = [
    # "pcie_aspm=force" # Forces Active State Power Management
    # "ahci.mobile_lpm_policy=3" # Aggressive Link Power Management for SATA
    # "i915.enable_fbc=1" # Framebuffer compression (if using iGPU)
    # "i915.enable_guc=3" # Enable GuC/HuC firmware loading
    "mitigations=off"
    "transparent_hugepage=never"
  ];
  boot.blacklistedKernelModules = ["bluetooth" "btusb" "snd_hda_intel" "soundcore" "snd_hda_codec" "snd_hwdep" "snd_pcm" "snd_timer" "snd_page_alloc" "uvcvideo" "videodev" "v4l2_common" " pcspkr"];

  services.scx = {
    enable = true;
    scheduler = "scx_cosmos";
    extraArgs = [
      "-s 20000"
      "-c 75"
      "-p 250"
    ];
  };
  # powerManagement.enable = true;
  # powerManagement.cpuFreqGovernor = "powersave";
  #
  # services.tlp = {
  #   enable = true;
  #   settings = {
  #     PCIE_ASPM_ON_AC = "powersave";
  #     SATA_LINKPWR_ON_AC = "min_power";
  #     CPU_MAX_PERF_ON_AC = 80;
  #     CPU_BOOST_ON_AC = 0;
  #   };
  # };
  # environment.systemPackages = with pkgs; [
  #   powertop
  #   cpufrequtils
  #   intel-gpu-tools
  # ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/2f797433-55b0-4556-aacc-0a8f3207b91e";
    fsType = "ext4";
  };

  fileSystems."/mnt/media" = {
    device = "/dev/disk/by-uuid/83608ae0-18b6-4ac9-bc6d-c56a9f6974e0";
    fsType = "ext4";
    options = [
      "users" # Allows any user to mount and unmount
      "nofail" # Prevent system from failing if this drive doesn't mount
      "exec" # Permit execution of binaries and other executable files
    ];
  };

  fileSystems."/mnt/media2" = {
    device = "/dev/disk/by-uuid/2816155e-0df7-4496-bce3-d1542139ad6c";
    fsType = "ext4";
    options = [
      "users" # Allows any user to mount and unmount
      "nofail" # Prevent system from failing if this drive doesn't mount
      "exec" # Permit execution of binaries and other executable files
    ];
  };
  swapDevices = [
    {device = "/dev/disk/by-uuid/9bd0bdcc-0aff-4eb2-a9d6-95ec28fff538";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
